django-shopping-cart-admin/ShoppingCartAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('ecommerce.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-shopping-cart-admin/ecommerce/urls.py
from django.urls import path
from . import views

app_name= 'ecommerce'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('product/<int:pk>', views. ProductView.as_view(), name='product'),
    path('cart', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout')
]

django-shopping-cart-admin/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register')
]

django-shopping-cart-admin/ecommerce/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db import transaction
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


from .utils import model_files_path


app_name = 'ecommerce'

# Create your models here.
class Currency(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    symbol = models.CharField(max_length=1)

    def __str__(self):
        return self.code + ' (' + self.name + ')'

    class Meta:
        verbose_name_plural = 'Currencies'


class Product(models.Model):
    name = models.CharField(max_length=255)
    sku = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=12)
    currency = models.ForeignKey(Currency, on_delete=models.DO_NOTHING)
    stock = models.IntegerField(default=0, editable=False)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(upload_to=model_files_path(file_type='image', model_name='products'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')


class ProductPurchase(models.Model):
    quantity = models.IntegerField()
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    readonly = ['created_at']
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        pk = self.pk
        with transaction.atomic():
            super().save(*args, **kwargs)
            if not pk:
                self.product.stock += self.quantity
                self.product.save()


class ProductSale(models.Model):

    quantity = models.IntegerField()
    unit_price = models.DecimalField(decimal_places=2, max_digits=12, editable=False)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    readonly = ['created_at']
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    IN_CART = 'C'
    IS_SOLD = 'S'

    status = models.CharField(max_length=1, default=IN_CART, choices=[
        (IN_CART, 'Cart'),
        (IS_SOLD, 'Sold')
    ])

    def save(self, *args, **kwargs):
        self.unit_price = self.product.price
        super().save(*args, **kwargs)

django-shopping-cart-admin/ecommerce/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from django.db import transaction
from django.db.models import F

from .models import Product, ProductSale

# Create your views here.
class IndexView(ListView):
    model = Product
    template_name = 'ecommerce/index.html'


class ProductView(DetailView):
    model = Product
    template_name = 'ecommerce/product.html'

def checkout(request):
    if request.method == 'POST':
        ProductSale.objects.filter(status=ProductSale.IN_CART, user=request.user).update(status=ProductSale.IS_SOLD)
    return render(request, 'ecommerce/cart.html', {'message': 'Payment Completed Successfully!'})

def cart(request):
    if request.method == 'GET':
        cart_items = ProductSale.objects.filter(status=ProductSale.IN_CART, user=request.user)
        return render(request, 'ecommerce/cart.html', {'cart_items': cart_items})

    else:
        quantity = int(request.POST['quantity'])
        product_id = int(request.POST['product_id'])
        product = Product.objects.get(pk=product_id)
        product_sale = ProductSale.objects.filter(product=product, user=request.user, status=ProductSale.IN_CART).first()

        if product_sale is not None:
            new_stock = 0
            if request.POST['_method'] == 'PUT':
                new_stock = product.stock - quantity + product_sale.quantity
            elif request.method == 'POST':
                new_stock = product.stock - quantity

            if new_stock < 0:
                return redirect('ecommerce:cart')
            product.stock = new_stock

            with transaction.atomic():
                product.save()

                if request.POST['_method'] == 'PUT':
                    product_sale.quantity = quantity
                elif request.method == 'POST':
                    product_sale.quantity += quantity

                if product_sale.quantity == 0:
                    product_sale.delete()
                else:
                    product_sale.save()

        else:
            if (quantity > 0) and (quantity <= product.stock):
                product_sale = ProductSale.objects.create(quantity=quantity, user=request.user, product=product)
                product.stock = F('stock') - quantity
                with transaction.atomic():
                    product.save()
                    product_sale.save()

    return redirect('ecommerce:cart')

django-shopping-cart-admin/ecommerce/templates/ecommerce/cart.html
{% extends 'ecommerce/template.html' %}

{% block content %}
    <div id="shopping-cart" class="mx-auto p-10 py-20 rounded-xl w-[80%] min-w[320px] min-h-[80vh]">
            <div class="flex justify-between">
                <h2 class="font-bold text-4xl text-gray-600">
                    Shopping Cart
                </h2>
                <form method="POST" action="{% url 'ecommerce:checkout' %}">
                    {% csrf_token %}
                    <button id="checkout-button" class="w-56"><i class="fas fa-check"></i> &nbsp; Complete Checkout</button>
                </form>
            </div>
            {% if message %}
                <h2 class="text-green-600 font-bold text-2xl my-20 text-center">{{ message }}</h2>
            {% endif %}
            {% if cart_items %}
                {% for item in cart_items %}
                    <div class="w-full flex items-center shadow-lg gap-5 px-10 py-10">
                        <div class="h-40 w-56 overflow-hidden bg-contain bg-center bg-no-repeat" style="background-image: url('/media/images/products/2022/06/02/71rXSVqET9L._AC_SL1257_.jpg')"></div>
                        <div class="">
                            <h2 class="font-bold text-gray-600">
                                {{ item.product.name }}
                            </h2>
                            <div>
                                <form action="{% url 'ecommerce:cart' %}" method="POST">
                                    {% csrf_token %}
                                    <input name="_method" value="PUT" type="hidden" />
                                    <input name="product_id" type="hidden" value="{{ item.product_id }}" />
                                    <div class="flex items-end">
                                        <div>
                                            <label for="quantity">Quantity:</label>
                                            <br/>
                                            <input name="quantity" id="quantity" type="number" class="quantity-input bg-gray-200 w-full rounded-l-lg w-36" value="{{ item.quantity }}" />
                                        </div>
                                        <button class="w-20 h-11 rounded-none rounded-r-lg">save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
    </div>
    <script>
        const checkButton = document.querySelector('#checkout-button')
        const setCheckoutDisabled = () => {
            checkButton.setAttribute('disabled', 'true')
            checkButton.setAttribute('class', 'bg-red-200 text-gray-700 hover:bg-gray-200 cursor-not-allowed w-56')
            checkButton.innerHTML = 'Save Your Changes First'
        }
        const cartContainer = document.querySelector('#shopping-cart')
        const events = ['keypress', 'change']
        events.forEach((event) => {
            cartContainer.addEventListener(event, (e) => {
                if(e.target.classList.contains('quantity-input')) {
                    setCheckoutDisabled();
                }
            })
        })
    </script>
{% endblock %}

django-shopping-cart-admin/ecommerce/templates/ecommerce/index.html
{% extends 'ecommerce/template.html' %}

{% block content %}
    <div class="mx-auto p-10 py-20 rounded-xl w-[80%] min-w[320px]">
            <div class="grid grid-cols-4 gap-5 w-full">
                {% for product in product_list %}
                    <div class="flex flex-col p-4 shadow-lg">
                        <a href="{% url 'ecommerce:product' pk=product.pk %}">
                            <div class="h-56 w-full overflow-hidden bg-contain bg-center bg-no-repeat " style="background-image: url('{{ product.images.first.image.url }}')"></div>
                            <h5 class="font-bold">
                                {{ product.name }}
                            </h5>
                            <span class="py-2 font-bold text-gray-400">
                                Price:
                                <span class="text-blue-600">
                                    {{ product.currency.symbol }}{{ product.price }}
                                </span>
                            </span>
                        </a>
                        {% if request.user.is_authenticated %}
                                {% if product.stock > 0 %}
                                    <form action="{% url 'ecommerce:cart' %}" method="POST" class="mt-5">
                                        {% csrf_token %}
                                        <input type="hidden" name="_method" value="POST" />
                                        <input name="quantity" id="quantity" type="hidden" class="bg-gray-200 w-full my-2 rounded-lg" value="1" />
                                        <input name="product_id" type="hidden" value="{{ product.pk }}" />
                                        <button class="w-full"><i class="fas fa-shopping-cart"></i> Add To Cart</button>
                                    </form>
                                {% else %}
                                    <button disabled class="bg-gray-200 mt-5 text-gray-700 hover:bg-gray-200 cursor-not-allowed w-full">Out Of Stock</button>
                                {% endif %}
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

django-shopping-cart-admin/ecommerce/templates/ecommerce/product.html
{% extends 'ecommerce/template.html' %}

{% block content %}
    <div class="mx-auto p-10 py-20 rounded-xl w-[80%] min-w[320px] shadow-lg min-h-[80vh]">
            <h2 class="font-bold text-4xl text-gray-600">
                {{ product.name }}
            </h2>
            <div class="p-10">
                <div class="h-56 w-full overflow-hidden bg-contain bg-center bg-no-repeat" style="background-image: url('{{ product.images.first.image.url }}')"></div>
            </div>
            <div class="grid grid-cols-3 gap-10 px-20 mt-10">
                <div class="col-span-2">
                    <h4 class="font-bold text-2xl text-gray-600">
                        Description:
                    </h4>
                    <p class="w-full text-lg my-5 mx-1 text-gray-600">
                        {{ product.description }}
                    </p>
                </div>
                <div>
                    <span class="font-bold text-2xl text-gray-500">
                        <i class="fas fa-truck"></i> {{ product.stock }} Piece{{ product.stock|pluralize }} Left
                    </span>
                    <span class="block my-2 text-4xl py-4 text-blue-500 w-[fit-content] h-[fit-content] rounded-lg">
                        <span class="font-bold">
                            Price:
                        </span>
                        <span>
                            {{ product.currency.symbol }}{{ product.price }}
                        </span>
                    </span>
                    {% if request.user.is_authenticated %}
                            {% if product.stock > 0 %}
                                <form action="{% url 'ecommerce:cart' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="_method" value="POST" />
                                    <label for="quantity">Quantity:</label>
                                    <input name="quantity" id="quantity" type="number" class="bg-gray-200 w-full my-2 rounded-lg" value="1" />
                                    <input name="product_id" type="hidden" value="{{ product.pk }}" />
                                    <button class="mt-2 w-full"><i class="fas fa-shopping-cart"></i> Add To Cart</button>
                                </form>
                            {% else %}
                                <button disabled class="bg-gray-200 mt-5 text-gray-700 hover:bg-gray-200 cursor-not-allowed w-full">Out Of Stock</button>
                            {% endif %}
                    {% endif %}
                </div>
            </div>
            <h4 class="font-bold text-2xl text-gray-600 px-20 mt-10">
                Gallery
            </h4>
            <div class="grid grid-cols-5 px-20">
                {% for product_image in product.images.all %}
                    <div class="p-5 shadow-md m-5">
                        <div class="h-32 w-full overflow-hidden bg-contain bg-center bg-no-repeat" style="background-image: url('{{ product_image.image.url }}')"></div>
                    </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

django-shopping-cart-admin/ecommerce/templates/ecommerce/template.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet"/>
    <style type="text/tailwindcss">
        @layer base {
            input {
                @apply p-2 outline-none text-lg bg-gray-100;
            }
            .errorlist {
                @apply text-red-400
            }
            input[type=submit], button {
                @apply text-white bg-blue-500 rounded-md py-2 hover:bg-blue-700 transition duration-500 cursor-pointer
            }
        }
    </style>
</head>
<body>
  <main>
    <nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800 w-full shadow-md py-5 relative">
      <div class="container flex flex-wrap justify-between items-center mx-auto">
        <a href="/" class="flex items-center">
            <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Shopping Cart</span>
        </a>
        <button data-collapse-toggle="mobile-menu" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
          <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
          <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
              {% if request.user.is_authenticated %}
                <li>
                  <p class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"><i class="fa fa-envelope"></i> {{ request.user.email }}</p>
                </li>
                <li>
                  <a href="{% url 'users:logout' %}" class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-red-500 md:p-0 dark:text-white"><i class="fa fa-sign-out"></i> Logout</a>
                </li>
              {% else %}
                <li>
                  <a href="{% url 'users:login' %}" class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Login</a>
                </li>
                <li>
                  <a href="{% url 'users:register' %}" class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Register</a>
                </li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
      <div class="container flex flex-wrap justify-between items-center mx-auto min-h-screen bg-white">
        {% block content %}

        {% endblock %}
      </div>
  </main>
</body>
</html>